"""relations

Revision ID: 2df6401b21a9
Revises: 0cd3328662e5
Create Date: 2024-11-18 08:32:11.760404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2df6401b21a9'
down_revision = '0cd3328662e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penyakit', schema=None) as batch_op:
        batch_op.drop_column('bobot_maks')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penyakit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bobot_maks', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
