"""data dialog5

Revision ID: 3d513be9e1c5
Revises: 
Create Date: 2024-11-17 08:02:13.325357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d513be9e1c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_kucing', sa.String(length=255), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=10), nullable=False),
    sa.Column('hasil_diagnosa', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gejala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_gejala', sa.String(length=10), nullable=False),
    sa.Column('gejala', sa.String(length=255), nullable=False),
    sa.Column('bobot', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_gejala')
    )
    op.create_table('penyakit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_penyakit', sa.String(length=255), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('penyakit_gejala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('penyakit_id', sa.Integer(), nullable=False),
    sa.Column('kode_gejala', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['kode_gejala'], ['gejala.kode_gejala'], ),
    sa.ForeignKeyConstraint(['penyakit_id'], ['penyakit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('penyakit_gejala')
    op.drop_table('user')
    op.drop_table('penyakit')
    op.drop_table('gejala')
    op.drop_table('diagnosa')
    # ### end Alembic commands ###
