"""add solusi to penyakit

Revision ID: 72c48cd1a38b
Revises: bb8899b0198a
Create Date: 2024-11-19 10:33:35.934448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c48cd1a38b'
down_revision = 'bb8899b0198a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penyakit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solusi', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penyakit', schema=None) as batch_op:
        batch_op.drop_column('solusi')

    # ### end Alembic commands ###
