"""add bobot_maks to penyakit

Revision ID: b7b58d0abef8
Revises: 3d513be9e1c5
Create Date: 2024-11-17 22:10:28.308512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b58d0abef8'
down_revision = '3d513be9e1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penyakit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bobot_maks', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('penyakit', schema=None) as batch_op:
        batch_op.drop_column('bobot_maks')

    # ### end Alembic commands ###
