"""hasil diagnosa

Revision ID: e461c3118ae4
Revises: 2df6401b21a9
Create Date: 2024-11-18 10:22:30.803139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e461c3118ae4'
down_revision = '2df6401b21a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gejala_dipilih', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnosa', schema=None) as batch_op:
        batch_op.drop_column('gejala_dipilih')

    # ### end Alembic commands ###
